package vistas;

import controladores.ControladorMascota;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Mascotas;

public class VentanaTablas extends javax.swing.JInternalFrame {
   private ControladorMascota mascotaControlador = new ControladorMascota();
    private DefaultTableModel modelo;

    // ✅ Constructor 1: Recibe un modelo (para compartir con otras ventanas)
    public VentanaTablas(DefaultTableModel modelo) {
        initComponents();
        this.modelo = modelo;
        tablaPacientes.setModel(modelo);
        ListarMascota();
    }

    // ✅ Constructor 2: Sin parámetros (crea su propio modelo)
    public VentanaTablas() {
        initComponents();
        modelo = new DefaultTableModel(
            new Object[]{"ID", "Nombre", "Especie", "Edad", "Documento Propietario"}, 0
        );
        tablaPacientes.setModel(modelo);
        ListarMascota();
    }

    // ✅ Método para llenar la tabla con las mascotas registradas
    public void ListarMascota() {
        modelo.setRowCount(0); // Limpia la tabla
        ArrayList<Mascotas> lista = mascotaControlador.obtenerTodasMascotas();

        if (lista != null) {
            for (Mascotas m : lista) {
                modelo.addRow(new Object[]{
                    m.getId(),
                    m.getNombre(),
                    m.getEspecie(),
                    m.getEdad(),
                    m.getDocumentoProp()
                });
            }
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Lista De Pacientes");

        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Especie", "Edad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaPacientes.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tablaPacientes);
        tablaPacientes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaPacientes;
    // End of variables declaration//GEN-END:variables

}